services:
  redis:
    image: redis:7-alpine
    deploy:
      replicas: ${DISK_COUNT:-1}
    ports:
      # The port mapping needs to be made manually
      - "6379-6381:6379"
#    command: redis-server --appendonly yes