// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=../../mocks/mock_store.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	block "disk-paxos/internal/block"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockStore) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockStoreMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStore)(nil).Close))
}

// DeleteAllBlocks mocks base method.
func (m *MockStore) DeleteAllBlocks(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllBlocks", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllBlocks indicates an expected call of DeleteAllBlocks.
func (mr *MockStoreMockRecorder) DeleteAllBlocks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllBlocks", reflect.TypeOf((*MockStore)(nil).DeleteAllBlocks), ctx)
}

// ReadAllBlocks mocks base method.
func (m *MockStore) ReadAllBlocks(ctx context.Context) ([]*block.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAllBlocks", ctx)
	ret0, _ := ret[0].([]*block.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAllBlocks indicates an expected call of ReadAllBlocks.
func (mr *MockStoreMockRecorder) ReadAllBlocks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAllBlocks", reflect.TypeOf((*MockStore)(nil).ReadAllBlocks), ctx)
}

// ReadBlocks mocks base method.
func (m *MockStore) ReadBlocks(ctx context.Context, ids ...int) ([]*block.Block, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range ids {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReadBlocks", varargs...)
	ret0, _ := ret[0].([]*block.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadBlocks indicates an expected call of ReadBlocks.
func (mr *MockStoreMockRecorder) ReadBlocks(ctx any, ids ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, ids...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadBlocks", reflect.TypeOf((*MockStore)(nil).ReadBlocks), varargs...)
}

// SetBlock mocks base method.
func (m *MockStore) SetBlock(ctx context.Context, id int, arg2 *block.Block) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBlock", ctx, id, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBlock indicates an expected call of SetBlock.
func (mr *MockStoreMockRecorder) SetBlock(ctx, id, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBlock", reflect.TypeOf((*MockStore)(nil).SetBlock), ctx, id, arg2)
}
